[auth]
redirect_uri = "http://localhost:8501/linear_dashboard/oauth2callback"
cookie_secret = ""

# Production redirect_uri:
# https://datalab.fanme.vn/linear_dashboard/oauth2callback

[auth.logto]
client_id = "yjkgil1hbg9qxwd1x1xmhd"
client_secret = "waPSuVuYtmO1raoziwLrU1e1K3sIGtDt"
server_metadata_url = "https://2lgb5y.logto.app/oidc/.well-known/openid-configuration"
client_kwargs = { scope = "openid profile email", prompt = "login" }
